In [1]:
import pandas as pd

In [2]:
'l1, l2, l3, l4'.split()

['l1,', 'l2,', 'l3,', 'l4']

In [3]:
data = [
    (1,2,3,4),
    (5,6,7,8),
    (8,10,11,12),
    (13,14,15,16)
]

df = pd.DataFrame(data, 'l1 l2 l3 l4'.split(), 'c1 c2 c3 c4'.split())
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   8  10  11  12
l4  13  14  15  16

In [4]:
df['c1']

l1     1
l2     5
l3     8
l4    13
Name: c1, dtype: int64

In [5]:
type(df['c1'])

pandas.core.series.Series

In [6]:
df[['c3', 'c1']]

    c3  c1
l1   3   1
l2   7   5
l3  11   8
l4  15  13

In [7]:
df[1:3]

    c1  c2  c3  c4
l2   5   6   7   8
l3   8  10  11  12

In [8]:
df[1:]

    c1  c2  c3  c4
l2   5   6   7   8
l3   8  10  11  12
l4  13  14  15  16

In [9]:
df[1:][['c3', 'c1']]

    c3  c1
l2   7   5
l3  11   8
l4  15  13

In [10]:
df.loc['l3']

c1     8
c2    10
c3    11
c4    12
Name: l3, dtype: int64

In [11]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   8  10  11  12
l4  13  14  15  16

In [12]:
df.loc[['l3', 'l2']]

    c1  c2  c3  c4
l3   8  10  11  12
l2   5   6   7   8

In [13]:
df.loc['l1','c2'] # Intersecciones

2

In [14]:
df.iloc[0, 1] # Alternativa a intersecciones

2

In [15]:
df.loc[['l3','l1'], ['c4','c1']]

    c4  c1
l3  12   8
l1   4   1

In [16]:
df.iloc[[2,0], [3,0]]

    c4  c1
l3  12   8
l1   4   1